### ISSUE TITLE
Convertir le texte brut en texte lisible/lié ?

### ISSUE THREAD

**Issue by davidbgk** [karlcow/travailtech#8]
Je viens de relire les minutes et @karlcow parle d'outils pour convertir les minutes, est-ce qu'il est possible de l'appliquer sur le texte brut ou au moins d'avoir un lien vers l'outil en question ?

Je pense que ce projet devrait continuer à vivre :)

**Comment by karlcow** [comment]
Ok. I will create a directory for the original version. Maybe olivier could add his version in python too.

**Comment by davidbgk** [comment]
Just a link to the online documentation of scribe: http://dev.w3.org/2002/scribe/scribedoc.htm

**Comment by olivierthereaux** [comment]
@karlcow yep. Still some cleaning up to do (my script has a bit of hardcoded junk I need to remove/substitute) but haven't forgotten about it (yet).

**Comment by olivierthereaux** [comment]
Done: https://github.com/karlcow/travailtech/tree/master/basic-scribe
